import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Daniel Park</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* introduction */}
        <div>
          {/* make it look it name tag */}
          <h2>Hello</h2>
          <h3>my name is</h3>
          <h1>Daniel</h1>
          <div>
            <img src="https://i.imgur.com/qwsAwsT.png"></img>
          </div>
        </div>
        {/* about me */}
        <div>
          <p>I'm a software engineer who loves motorcycles and video games. Riding my bike and gaming keep me energized and focused when I'm coding. </p>
        </div>
        {/* Skills */}
        <div>
          <div>
            languages - JavaScript · HTML5 · CSS · Python
          </div>
          <div>
            skills - Node.js · Express.js · React.js · Full-Stack Development · SQL · MongoDB · Autodesk Maya · Unreal Engine · Adobe Illustrator · Adobe Photoshop
          </div>
        </div>
      </div>
    </>
  )
}
