import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Portfolio from './portfolio'
import Aboutme from './Aboutme'
import Intro from './Intro'
import Techs from './Techs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.coolColor}>
      <Head>
        <title>Daniel Park</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* introduction */}
        <Intro/>

        {/* about me */}
        <Aboutme />

        {/* Techs */}
        <Techs />

        {/* Projects */}
        <Portfolio />
        
      </div>
    </div>
  )
}
