import Head from 'next/head'
import { Inter } from '@next/font/google'

import Portfolio from './portfolio'
import Aboutme from './Aboutme'
import Intro from './Intro'
import Techs from './Techs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Daniel Park</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* introduction */}
        <Intro/>
      </div>

      <div id="aboutMe">
        {/* about me */}
        <Aboutme />
      </div>

      <div id="techs">
        {/* Techs */}
        <Techs />
      </div>
      
      <div id="projects">
        {/* Projects */}
        <Portfolio />
      </div>

    </div>
  )
}
